version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crud_network

  # Spring Boot Application Service
  springboot-app:
    image: open_ai_integration-image:latest  # Replace with your Docker image name
    container_name: open_ai_integration_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/products
      SPRING_DATASOURCE_USERNAME: ${USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - crud_network

# Volumes for persistent data storage
volumes:
  postgres_data:

# Network for communication between services
networks:
  crud_network:
    driver: bridge